/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119010-ge5a33c898a-20250326"
#endif /* AVUTIL_FFVERSION_H */
